update=16/11/2013 5:40:00 p.m.
last_client=pcbnew
[common]
NetDir=
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=H:/S6_BOARD2/Ants Librarys
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/00N8VEM
LibName2=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/4MEM-cache
LibName3=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/65xxx
LibName4=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/74ls-sergey
LibName5=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/74xx
LibName6=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/8563
LibName7=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/babyM68K-cache
LibName8=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/con-headers-jp
LibName9=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/conn
LibName10=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/con-vg
LibName11=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/dallas-rtc
LibName12=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/devices-sergey
LibName13=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/dips-s
LibName14=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/display-hp
LibName15=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_connectors
LibName16=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_switches
LibName17=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/ECB-4PIO-cache
LibName18=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/ECB-RAF2011-R08-cache
LibName19=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/gd5420
LibName20=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/HD15_B
LibName21=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName22=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName23=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/intel
LibName24=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/intel-8xxx
LibName25=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/led
LibName26=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/lm334z
LibName27=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/lumiled
LibName28=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/maxim
LibName29=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/mcm414256-dip20
LibName30=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/memory
LibName31=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/memory-sergey
LibName32=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip
LibName33=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_can
LibName34=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_enet
LibName35=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName36=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName37=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip1
LibName38=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-2
LibName39=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName40=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName41=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName42=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName43=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName44=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName45=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName46=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/micro-mc68000
LibName47=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName48=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/mini_din
LibName49=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/motorola
LibName50=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/N8VEM-KiCAD
LibName51=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_analog
LibName52=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_intel
LibName53=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_memory
LibName54=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_moto
LibName55=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_ttl
LibName56=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_zilog
LibName57=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/oldchips
LibName58=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/opendous
LibName59=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/P112-parts
LibName60=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/PIC-004-cache
LibName61=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/pic18f67j60
LibName62=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/propeller
LibName63=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/ref-packages
LibName64=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/renesas21
LibName65=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/s100_Z80-cache
LibName66=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/SBC-188
LibName67=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs
LibName68=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-2
LibName69=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-eth
LibName70=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/sn2032
LibName71=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/special
LibName72=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/tms9918-AY38910
LibName73=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor
LibName74=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor-power
LibName75=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/upd7220
LibName76=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName77=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/XC9572XL_44Pin-cache
LibName78=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/XILINX
LibName79=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName80=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName81=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinxMOD1
LibName82=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/Z8S180
LibName83=F:/Documents/Ants Librarys/ALL other libs apart from ANTS_MOD1/z53c80
LibName84=F:/Documents/Ants Librarys/KiCAD Libraries/74xx
LibName85=F:/Documents/Ants Librarys/KiCAD Libraries/adc-dac
LibName86=F:/Documents/Ants Librarys/KiCAD Libraries/analog_switches
LibName87=F:/Documents/Ants Librarys/KiCAD Libraries/atmel
LibName88=F:/Documents/Ants Librarys/KiCAD Libraries/audio
LibName89=F:/Documents/Ants Librarys/KiCAD Libraries/brooktre
LibName90=F:/Documents/Ants Librarys/KiCAD Libraries/cmos_ieee
LibName91=F:/Documents/Ants Librarys/KiCAD Libraries/cmos4000
LibName92=F:/Documents/Ants Librarys/KiCAD Libraries/conn
LibName93=F:/Documents/Ants Librarys/KiCAD Libraries/contrib
LibName94=F:/Documents/Ants Librarys/KiCAD Libraries/cypress
LibName95=F:/Documents/Ants Librarys/KiCAD Libraries/device
LibName96=F:/Documents/Ants Librarys/KiCAD Libraries/digital-audio
LibName97=F:/Documents/Ants Librarys/KiCAD Libraries/display
LibName98=F:/Documents/Ants Librarys/KiCAD Libraries/dsp
LibName99=F:/Documents/Ants Librarys/KiCAD Libraries/gennum
LibName100=F:/Documents/Ants Librarys/KiCAD Libraries/graphic
LibName101=F:/Documents/Ants Librarys/KiCAD Libraries/intel
LibName102=F:/Documents/Ants Librarys/KiCAD Libraries/interface
LibName103=F:/Documents/Ants Librarys/KiCAD Libraries/linear
LibName104=F:/Documents/Ants Librarys/KiCAD Libraries/memory
LibName105=F:/Documents/Ants Librarys/KiCAD Libraries/microchip
LibName106=F:/Documents/Ants Librarys/KiCAD Libraries/microchip1
LibName107=F:/Documents/Ants Librarys/KiCAD Libraries/microcontrollers
LibName108=F:/Documents/Ants Librarys/KiCAD Libraries/motorola
LibName109=F:/Documents/Ants Librarys/KiCAD Libraries/opto
LibName110=F:/Documents/Ants Librarys/KiCAD Libraries/philips
LibName111=F:/Documents/Ants Librarys/KiCAD Libraries/power
LibName112=F:/Documents/Ants Librarys/KiCAD Libraries/pspice
LibName113=F:/Documents/Ants Librarys/KiCAD Libraries/regul
LibName114=F:/Documents/Ants Librarys/KiCAD Libraries/siliconi
LibName115=F:/Documents/Ants Librarys/KiCAD Libraries/special
LibName116=F:/Documents/Ants Librarys/KiCAD Libraries/SymbolsSimilarEN60617+oldDIN617
LibName117=F:/Documents/Ants Librarys/KiCAD Libraries/texas
LibName118=F:/Documents/Ants Librarys/KiCAD Libraries/transf
LibName119=F:/Documents/Ants Librarys/KiCAD Libraries/transistors
LibName120=F:/Documents/Ants Librarys/KiCAD Libraries/ttl_ieee
LibName121=F:/Documents/Ants Librarys/KiCAD Libraries/valves
LibName122=F:/Documents/Ants Librarys/KiCAD Libraries/video
LibName123=F:/Documents/Ants Librarys/KiCAD Libraries/xilinx
LibName124=F:/Documents/Ants Librarys/KiCAD Libraries/xxx
LibName125=F:/Documents/Ants Librarys/ANTS_MOD1
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.000000000000
PadDrillOvalY=0.000000000000
PadSizeH=0.998220000000
PadSizeV=1.399540000000
PcbTextSizeV=2.032000000000
PcbTextSizeH=1.524000000000
PcbTextThickness=0.304800000000
ModuleTextSizeV=1.524000000000
ModuleTextSizeH=1.524000000000
ModuleTextSizeThickness=0.304800000000
SolderMaskClearance=0.254000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.100000000000
BoardOutlineThickness=0.381000000000
ModuleOutlineThickness=0.381000000000
[pcbnew/libraries]
LibDir=../Ants Librarys;../Ants Librarys
LibName1=ALL other libs apart from ANTS_MOD1/65xxx
LibName2=ALL other libs apart from ANTS_MOD1/connecteurs
LibName3=ALL other libs apart from ANTS_MOD1/con-vg
LibName4=ALL other libs apart from ANTS_MOD1/dbrothers
LibName5=ALL other libs apart from ANTS_MOD1/diode
LibName6=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName7=ALL other libs apart from ANTS_MOD1/diy_switches
LibName8=ALL other libs apart from ANTS_MOD1/HD15_B
LibName9=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName10=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName11=ALL other libs apart from ANTS_MOD1/led
LibName12=ALL other libs apart from ANTS_MOD1/lumiled
LibName13=ALL other libs apart from ANTS_MOD1/maxim
LibName14=ALL other libs apart from ANTS_MOD1/microchip
LibName15=ALL other libs apart from ANTS_MOD1/microchip_can
LibName16=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName17=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName18=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName19=ALL other libs apart from ANTS_MOD1/microchip-2
LibName20=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName21=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName22=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName23=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName24=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName25=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName26=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName27=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName28=ALL other libs apart from ANTS_MOD1/mini_din
LibName29=ALL other libs apart from ANTS_MOD1/N8VEM
LibName30=ALL other libs apart from ANTS_MOD1/national
LibName31=ALL other libs apart from ANTS_MOD1/oldchips
LibName32=ALL other libs apart from ANTS_MOD1/opendous
LibName33=ALL other libs apart from ANTS_MOD1/propeller
LibName34=ALL other libs apart from ANTS_MOD1/RCA_video_jack
LibName35=ALL other libs apart from ANTS_MOD1/ref-packages
LibName36=ALL other libs apart from ANTS_MOD1/renesas21
LibName37=ALL other libs apart from ANTS_MOD1/S100connector
LibName38=ALL other libs apart from ANTS_MOD1/silabs
LibName39=ALL other libs apart from ANTS_MOD1/silabs-2
LibName40=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName41=ALL other libs apart from ANTS_MOD1/sn2032
LibName42=ALL other libs apart from ANTS_MOD1/stereo_jack
LibName43=ALL other libs apart from ANTS_MOD1/supports
LibName44=ALL other libs apart from ANTS_MOD1/transistor
LibName45=ALL other libs apart from ANTS_MOD1/transistor-power
LibName46=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName47=ALL other libs apart from ANTS_MOD1/XILINX
LibName48=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName49=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName50=numato/numato_kicad_lib
LibName51=KiCAD Libraries/capacitors
LibName52=KiCAD Libraries/connect
LibName53=KiCAD Libraries/connectors_molex_serial_53047-A123
LibName54=KiCAD Libraries/dip_sockets
LibName55=KiCAD Libraries/discret
LibName56=KiCAD Libraries/display
LibName57=KiCAD Libraries/divers
LibName58=KiCAD Libraries/inductors
LibName59=KiCAD Libraries/led
LibName60=KiCAD Libraries/libcms
LibName61=KiCAD Libraries/muonde
LibName62=KiCAD Libraries/pga_sockets
LibName63=KiCAD Libraries/pin_array
LibName64=KiCAD Libraries/powerint
LibName65=KiCAD Libraries/smd_capacitors
LibName66=KiCAD Libraries/smd_crystal&oscillator
LibName67=KiCAD Libraries/smd_dil
LibName68=KiCAD Libraries/smd_resistors
LibName69=KiCAD Libraries/smd_soic_packages
LibName70=KiCAD Libraries/smd_ssop_packages
LibName71=KiCAD Libraries/smd_transistors
LibName72=KiCAD Libraries/sockets
LibName73=KiCAD Libraries/valves
LibName74=ANTS1/ANTS1
