update=10/30/2013 1:05:08 AM
last_client=pcbnew
[common]
NetDir=
[eeschema]
version=1
LibDir=H:/S6_BOARD2/Ants Librarys
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=ANTS_MOD1
LibName2=ALL other libs apart from ANTS_MOD1/00N8VEM
LibName3=ALL other libs apart from ANTS_MOD1/4MEM-cache
LibName4=ALL other libs apart from ANTS_MOD1/65xxx
LibName5=ALL other libs apart from ANTS_MOD1/8563
LibName6=ALL other libs apart from ANTS_MOD1/babyM68K-cache
LibName7=ALL other libs apart from ANTS_MOD1/con-headers-jp
LibName8=ALL other libs apart from ANTS_MOD1/conn
LibName9=ALL other libs apart from ANTS_MOD1/con-vg
LibName10=ALL other libs apart from ANTS_MOD1/dips-s
LibName11=ALL other libs apart from ANTS_MOD1/display-hp
LibName12=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName13=ALL other libs apart from ANTS_MOD1/diy_switches
LibName14=ALL other libs apart from ANTS_MOD1/ECB-4PIO-cache
LibName15=ALL other libs apart from ANTS_MOD1/ECB-RAF2011-R08-cache
LibName16=ALL other libs apart from ANTS_MOD1/gd5420
LibName17=ALL other libs apart from ANTS_MOD1/HD15_B
LibName18=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName19=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName20=ALL other libs apart from ANTS_MOD1/intel
LibName21=ALL other libs apart from ANTS_MOD1/led
LibName22=ALL other libs apart from ANTS_MOD1/lm334z
LibName23=ALL other libs apart from ANTS_MOD1/lumiled
LibName24=ALL other libs apart from ANTS_MOD1/maxim
LibName25=ALL other libs apart from ANTS_MOD1/mcm414256-dip20
LibName26=ALL other libs apart from ANTS_MOD1/memory
LibName27=ALL other libs apart from ANTS_MOD1/microchip
LibName28=ALL other libs apart from ANTS_MOD1/microchip_can
LibName29=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName30=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName31=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName32=ALL other libs apart from ANTS_MOD1/microchip1
LibName33=ALL other libs apart from ANTS_MOD1/microchip-2
LibName34=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName35=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName36=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName37=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName38=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName39=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName40=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName41=ALL other libs apart from ANTS_MOD1/micro-mc68000
LibName42=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName43=ALL other libs apart from ANTS_MOD1/mini_din
LibName44=ALL other libs apart from ANTS_MOD1/motorola
LibName45=ALL other libs apart from ANTS_MOD1/N8VEM-KiCAD
LibName46=ALL other libs apart from ANTS_MOD1/o_analog
LibName47=ALL other libs apart from ANTS_MOD1/o_intel
LibName48=ALL other libs apart from ANTS_MOD1/o_memory
LibName49=ALL other libs apart from ANTS_MOD1/o_moto
LibName50=ALL other libs apart from ANTS_MOD1/o_ttl
LibName51=ALL other libs apart from ANTS_MOD1/o_zilog
LibName52=ALL other libs apart from ANTS_MOD1/oldchips
LibName53=ALL other libs apart from ANTS_MOD1/opendous
LibName54=ALL other libs apart from ANTS_MOD1/P112-parts
LibName55=ALL other libs apart from ANTS_MOD1/PIC-004-cache
LibName56=ALL other libs apart from ANTS_MOD1/pic18f67j60
LibName57=ALL other libs apart from ANTS_MOD1/propeller
LibName58=ALL other libs apart from ANTS_MOD1/ref-packages
LibName59=ALL other libs apart from ANTS_MOD1/renesas21
LibName60=ALL other libs apart from ANTS_MOD1/s100_Z80-cache
LibName61=ALL other libs apart from ANTS_MOD1/SBC-188
LibName62=ALL other libs apart from ANTS_MOD1/silabs
LibName63=ALL other libs apart from ANTS_MOD1/silabs-2
LibName64=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName65=ALL other libs apart from ANTS_MOD1/sn2032
LibName66=ALL other libs apart from ANTS_MOD1/special
LibName67=ALL other libs apart from ANTS_MOD1/tms9918-AY38910
LibName68=ALL other libs apart from ANTS_MOD1/transistor
LibName69=ALL other libs apart from ANTS_MOD1/transistor-power
LibName70=ALL other libs apart from ANTS_MOD1/upd7220
LibName71=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName72=ALL other libs apart from ANTS_MOD1/XC9572XL_44Pin-cache
LibName73=ALL other libs apart from ANTS_MOD1/XILINX
LibName74=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName75=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName76=ALL other libs apart from ANTS_MOD1/xilinxMOD1
LibName77=ALL other libs apart from ANTS_MOD1/Z8S180
LibName78=ALL other libs apart from ANTS_MOD1/z53c80
LibName79=numato/numato_kicad_lib
LibName80=ALL other libs apart from ANTS_MOD1/74ls-sergey
LibName81=ALL other libs apart from ANTS_MOD1/devices-sergey
LibName82=C:/Users/user/Documents/ISA Backplane/isa_backplane-KiCad-1.1/isa_backplane-cache
LibName83=ALL other libs apart from ANTS_MOD1/74xx
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=S100-Backplane.net
UseCmpFile=1
PadDrill=1.000000000000
PadDrillOvalY=1.000000000000
PadSizeH=1.800000000000
PadSizeV=1.800000000000
PcbTextSizeV=2.032000000000
PcbTextSizeH=1.524000000000
PcbTextThickness=0.304800000000
ModuleTextSizeV=1.524000000000
ModuleTextSizeH=1.524000000000
ModuleTextSizeThickness=0.304800000000
SolderMaskClearance=0.254000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.100000000000
BoardOutlineThickness=0.381000000000
ModuleOutlineThickness=0.381000000000
[pcbnew/libraries]
LibDir=../Ants Librarys;../Ants Librarys
LibName1=ALL other libs apart from ANTS_MOD1/65xxx
LibName2=ALL other libs apart from ANTS_MOD1/connecteurs
LibName3=ALL other libs apart from ANTS_MOD1/con-vg
LibName4=ALL other libs apart from ANTS_MOD1/dbrothers
LibName5=ALL other libs apart from ANTS_MOD1/diode
LibName6=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName7=ALL other libs apart from ANTS_MOD1/diy_switches
LibName8=ALL other libs apart from ANTS_MOD1/HD15_B
LibName9=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName10=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName11=ALL other libs apart from ANTS_MOD1/led
LibName12=ALL other libs apart from ANTS_MOD1/lumiled
LibName13=ALL other libs apart from ANTS_MOD1/maxim
LibName14=ALL other libs apart from ANTS_MOD1/microchip
LibName15=ALL other libs apart from ANTS_MOD1/microchip_can
LibName16=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName17=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName18=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName19=ALL other libs apart from ANTS_MOD1/microchip-2
LibName20=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName21=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName22=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName23=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName24=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName25=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName26=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName27=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName28=ALL other libs apart from ANTS_MOD1/mini_din
LibName29=ALL other libs apart from ANTS_MOD1/N8VEM
LibName30=ALL other libs apart from ANTS_MOD1/national
LibName31=ALL other libs apart from ANTS_MOD1/oldchips
LibName32=ALL other libs apart from ANTS_MOD1/opendous
LibName33=ALL other libs apart from ANTS_MOD1/propeller
LibName34=ALL other libs apart from ANTS_MOD1/RCA_video_jack
LibName35=ALL other libs apart from ANTS_MOD1/ref-packages
LibName36=ALL other libs apart from ANTS_MOD1/renesas21
LibName37=ALL other libs apart from ANTS_MOD1/S100connector
LibName38=ALL other libs apart from ANTS_MOD1/silabs
LibName39=ALL other libs apart from ANTS_MOD1/silabs-2
LibName40=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName41=ALL other libs apart from ANTS_MOD1/sn2032
LibName42=ALL other libs apart from ANTS_MOD1/stereo_jack
LibName43=ALL other libs apart from ANTS_MOD1/supports
LibName44=ALL other libs apart from ANTS_MOD1/transistor
LibName45=ALL other libs apart from ANTS_MOD1/transistor-power
LibName46=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName47=ALL other libs apart from ANTS_MOD1/XILINX
LibName48=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName49=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName50=numato/numato_kicad_lib
LibName51=KiCAD Libraries/capacitors
LibName52=KiCAD Libraries/connect
LibName53=KiCAD Libraries/connectors_molex_serial_53047-A123
LibName54=KiCAD Libraries/dip_sockets
LibName55=KiCAD Libraries/discret
LibName56=KiCAD Libraries/display
LibName57=KiCAD Libraries/divers
LibName58=KiCAD Libraries/inductors
LibName59=KiCAD Libraries/led
LibName60=KiCAD Libraries/libcms
LibName61=KiCAD Libraries/muonde
LibName62=KiCAD Libraries/pga_sockets
LibName63=KiCAD Libraries/pin_array
LibName64=KiCAD Libraries/powerint
LibName65=KiCAD Libraries/smd_capacitors
LibName66=KiCAD Libraries/smd_crystal&oscillator
LibName67=KiCAD Libraries/smd_dil
LibName68=KiCAD Libraries/smd_resistors
LibName69=KiCAD Libraries/smd_soic_packages
LibName70=KiCAD Libraries/smd_ssop_packages
LibName71=KiCAD Libraries/smd_transistors
LibName72=KiCAD Libraries/sockets
LibName73=KiCAD Libraries/valves
LibName74=ANTS1/ANTS1
