update=8/3/2013 2:25:22 AM
last_client=cvpcb
[common]
NetDir=
[pcbnew]
version=1
PadDrlX=1200
PadDimH=3500
PadDimV=3500
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=S100-Backplane.net
[pcbnew/libraries]
LibName1=connect
LibName2=discret
LibName3=pin_array
LibName4=divers
LibName5=libcms
LibName6=display
LibName7=valves
LibName8=ALL other libs apart from ANTS_MOD1/S100connector
LibName9=ALL other libs apart from ANTS_MOD1/supports
LibName10=ALL other libs apart from ANTS_MOD1/XILINX
LibName11=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName12=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName13=ALL other libs apart from ANTS_MOD1/ref-packages
LibName14=ANTS1/ANTS1
LibDir=H:/S6_BOARD2/Ants Librarys
[eeschema]
version=1
LibDir=H:/S6_BOARD2/Ants Librarys
NetFmt=1
HPGLSpd=20
HPGLDm=15
HPGLNum=1
offX_A4=0
offY_A4=0
offX_A3=0
offY_A3=0
offX_A2=0
offY_A2=0
offX_A1=0
offY_A1=0
offX_A0=0
offY_A0=0
offX_A=0
offY_A=0
offX_B=0
offY_B=0
offX_C=0
offY_C=0
offX_D=0
offY_D=0
offX_E=0
offY_E=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=ANTS_MOD1
LibName2=ALL other libs apart from ANTS_MOD1/00N8VEM
LibName3=ALL other libs apart from ANTS_MOD1/4MEM-cache
LibName4=ALL other libs apart from ANTS_MOD1/65xxx
LibName5=ALL other libs apart from ANTS_MOD1/74xx
LibName6=ALL other libs apart from ANTS_MOD1/8563
LibName7=ALL other libs apart from ANTS_MOD1/babyM68K-cache
LibName8=ALL other libs apart from ANTS_MOD1/con-headers-jp
LibName9=ALL other libs apart from ANTS_MOD1/conn
LibName10=ALL other libs apart from ANTS_MOD1/con-vg
LibName11=ALL other libs apart from ANTS_MOD1/dips-s
LibName12=ALL other libs apart from ANTS_MOD1/display-hp
LibName13=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName14=ALL other libs apart from ANTS_MOD1/diy_switches
LibName15=ALL other libs apart from ANTS_MOD1/ECB-4PIO-cache
LibName16=ALL other libs apart from ANTS_MOD1/ECB-RAF2011-R08-cache
LibName17=ALL other libs apart from ANTS_MOD1/gd5420
LibName18=ALL other libs apart from ANTS_MOD1/HD15_B
LibName19=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName20=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName21=ALL other libs apart from ANTS_MOD1/intel
LibName22=ALL other libs apart from ANTS_MOD1/led
LibName23=ALL other libs apart from ANTS_MOD1/lm334z
LibName24=ALL other libs apart from ANTS_MOD1/lumiled
LibName25=ALL other libs apart from ANTS_MOD1/maxim
LibName26=ALL other libs apart from ANTS_MOD1/mcm414256-dip20
LibName27=ALL other libs apart from ANTS_MOD1/memory
LibName28=ALL other libs apart from ANTS_MOD1/microchip
LibName29=ALL other libs apart from ANTS_MOD1/microchip_can
LibName30=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName31=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName32=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName33=ALL other libs apart from ANTS_MOD1/microchip1
LibName34=ALL other libs apart from ANTS_MOD1/microchip-2
LibName35=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName36=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName37=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName38=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName39=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName40=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName41=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName42=ALL other libs apart from ANTS_MOD1/micro-mc68000
LibName43=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName44=ALL other libs apart from ANTS_MOD1/mini_din
LibName45=ALL other libs apart from ANTS_MOD1/motorola
LibName46=ALL other libs apart from ANTS_MOD1/N8VEM-KiCAD
LibName47=ALL other libs apart from ANTS_MOD1/o_analog
LibName48=ALL other libs apart from ANTS_MOD1/o_intel
LibName49=ALL other libs apart from ANTS_MOD1/o_memory
LibName50=ALL other libs apart from ANTS_MOD1/o_moto
LibName51=ALL other libs apart from ANTS_MOD1/o_ttl
LibName52=ALL other libs apart from ANTS_MOD1/o_zilog
LibName53=ALL other libs apart from ANTS_MOD1/oldchips
LibName54=ALL other libs apart from ANTS_MOD1/opendous
LibName55=ALL other libs apart from ANTS_MOD1/P112-parts
LibName56=ALL other libs apart from ANTS_MOD1/PIC-004-cache
LibName57=ALL other libs apart from ANTS_MOD1/pic18f67j60
LibName58=ALL other libs apart from ANTS_MOD1/propeller
LibName59=ALL other libs apart from ANTS_MOD1/ref-packages
LibName60=ALL other libs apart from ANTS_MOD1/renesas21
LibName61=ALL other libs apart from ANTS_MOD1/s100_Z80-cache
LibName62=ALL other libs apart from ANTS_MOD1/SBC-188
LibName63=ALL other libs apart from ANTS_MOD1/silabs
LibName64=ALL other libs apart from ANTS_MOD1/silabs-2
LibName65=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName66=ALL other libs apart from ANTS_MOD1/sn2032
LibName67=ALL other libs apart from ANTS_MOD1/special
LibName68=ALL other libs apart from ANTS_MOD1/tms9918-AY38910
LibName69=ALL other libs apart from ANTS_MOD1/transistor
LibName70=ALL other libs apart from ANTS_MOD1/transistor-power
LibName71=ALL other libs apart from ANTS_MOD1/upd7220
LibName72=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName73=ALL other libs apart from ANTS_MOD1/XC9572XL_44Pin-cache
LibName74=ALL other libs apart from ANTS_MOD1/XILINX
LibName75=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName76=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName77=ALL other libs apart from ANTS_MOD1/xilinxMOD1
LibName78=ALL other libs apart from ANTS_MOD1/Z8S180
LibName79=ALL other libs apart from ANTS_MOD1/z53c80
LibName80=numato/numato_kicad_lib
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
