update=03-08-14 11:18 AM
last_client=cvpcb
[common]
NetDir=
[pcbnew]
version=1
LastNetListRead=
PadDrlX=320
PadDimH=600
PadDimV=600
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
[pcbnew/libraries]
LibName1=supports
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=N8VEM-KiCAD-005/N8VEM-KiCAD/S100connector
LibName10=ANTS1/ANTS1
LibName11=ALL other libs apart from ANTS_MOD1/65xxx
LibName12=ALL other libs apart from ANTS_MOD1/connecteurs
LibName13=ALL other libs apart from ANTS_MOD1/con-vg
LibName14=ALL other libs apart from ANTS_MOD1/dbrothers
LibName15=ALL other libs apart from ANTS_MOD1/diode
LibName16=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName17=ALL other libs apart from ANTS_MOD1/diy_switches
LibName18=ALL other libs apart from ANTS_MOD1/HD15_B
LibName19=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName20=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName21=ALL other libs apart from ANTS_MOD1/led
LibName22=ALL other libs apart from ANTS_MOD1/lumiled
LibName23=ALL other libs apart from ANTS_MOD1/maxim
LibName24=ALL other libs apart from ANTS_MOD1/microchip
LibName25=ALL other libs apart from ANTS_MOD1/microchip_can
LibName26=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName27=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName28=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName29=ALL other libs apart from ANTS_MOD1/microchip-2
LibName30=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName31=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName32=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName33=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName34=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName35=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName36=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName37=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName38=ALL other libs apart from ANTS_MOD1/mini_din
LibName39=ALL other libs apart from ANTS_MOD1/N8VEM
LibName40=ALL other libs apart from ANTS_MOD1/national
LibName41=ALL other libs apart from ANTS_MOD1/oldchips
LibName42=ALL other libs apart from ANTS_MOD1/opendous
LibName43=ALL other libs apart from ANTS_MOD1/propeller
LibName44=ALL other libs apart from ANTS_MOD1/RCA_video_jack
LibName45=ALL other libs apart from ANTS_MOD1/ref-packages
LibName46=ALL other libs apart from ANTS_MOD1/renesas21
LibName47=ALL other libs apart from ANTS_MOD1/S100connector
LibName48=ALL other libs apart from ANTS_MOD1/silabs
LibName49=ALL other libs apart from ANTS_MOD1/silabs-2
LibName50=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName51=ALL other libs apart from ANTS_MOD1/sn2032
LibName52=ALL other libs apart from ANTS_MOD1/stereo_jack
LibName53=ALL other libs apart from ANTS_MOD1/supports
LibName54=ALL other libs apart from ANTS_MOD1/transistor
LibName55=ALL other libs apart from ANTS_MOD1/transistor-power
LibName56=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName57=ALL other libs apart from ANTS_MOD1/XILINX
LibName58=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName59=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName60=KiCAD Libraries/dip_sockets
LibName61=N8VEM-KiCAD-005/N8VEM-KiCAD/molex-drive-connector
LibDir=C:/Users/user/Desktop/Ants Librarys
[eeschema]
version=1
LibDir=C:/Users/user/Desktop/Ants Librarys
NetFmtName=Pcbnew
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=conn
LibName4=linear
LibName5=regul
LibName6=74xx
LibName7=cmos4000
LibName8=adc-dac
LibName9=memory
LibName10=xilinx
LibName11=special
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=contrib
LibName27=valves
LibName28=ANTS_MOD1
LibName29=N8VEM-KiCAD-005/N8VEM-KiCAD/00N8VEM
LibName30=N8VEM-KiCAD-005/N8VEM-KiCAD/o_analog
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
