update=9/5/2013 8:10:22 PM
last_client=eeschema
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=SBC.net
UseCmpFile=1
PadDrill=0.000000000000
PadDrillOvalY=0.000000000000
PadSizeH=0.701040000000
PadSizeV=1.000760000000
PcbTextSizeV=2.032000000000
PcbTextSizeH=1.524000000000
PcbTextThickness=0.304800000000
ModuleTextSizeV=1.524000000000
ModuleTextSizeH=1.524000000000
ModuleTextSizeThickness=0.304800000000
SolderMaskClearance=0.254000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.100000000000
BoardOutlineThickness=0.381000000000
ModuleOutlineThickness=0.381000000000
[pcbnew/libraries]
LibDir=../../Ants Librarys
LibName1=KiCAD Libraries/capacitors
LibName2=KiCAD Libraries/connect
LibName3=KiCAD Libraries/connectors_molex_serial_53047-A123
LibName4=KiCAD Libraries/dip_sockets
LibName5=KiCAD Libraries/discret
LibName6=KiCAD Libraries/display
LibName7=KiCAD Libraries/divers
LibName8=KiCAD Libraries/inductors
LibName9=KiCAD Libraries/led
LibName10=KiCAD Libraries/libcms
LibName11=KiCAD Libraries/muonde
LibName12=KiCAD Libraries/pga_sockets
LibName13=KiCAD Libraries/pin_array
LibName14=KiCAD Libraries/powerint
LibName15=KiCAD Libraries/smd_capacitors
LibName16=KiCAD Libraries/smd_crystal&oscillator
LibName17=KiCAD Libraries/smd_dil
LibName18=KiCAD Libraries/smd_resistors
LibName19=KiCAD Libraries/smd_soic_packages
LibName20=KiCAD Libraries/smd_ssop_packages
LibName21=KiCAD Libraries/smd_transistors
LibName22=KiCAD Libraries/sockets
LibName23=KiCAD Libraries/valves
LibName24=ALL other libs apart from ANTS_MOD1/65xxx
LibName25=ALL other libs apart from ANTS_MOD1/connecteurs
LibName26=ALL other libs apart from ANTS_MOD1/con-vg
LibName27=ALL other libs apart from ANTS_MOD1/dbrothers
LibName28=ALL other libs apart from ANTS_MOD1/diode
LibName29=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName30=ALL other libs apart from ANTS_MOD1/diy_switches
LibName31=ALL other libs apart from ANTS_MOD1/HD15_B
LibName32=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName33=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName34=ALL other libs apart from ANTS_MOD1/led
LibName35=ALL other libs apart from ANTS_MOD1/lumiled
LibName36=ALL other libs apart from ANTS_MOD1/maxim
LibName37=ALL other libs apart from ANTS_MOD1/microchip
LibName38=ALL other libs apart from ANTS_MOD1/microchip_can
LibName39=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName40=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName41=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName42=ALL other libs apart from ANTS_MOD1/microchip-2
LibName43=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName44=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName45=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName46=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName47=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName48=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName49=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName50=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName51=ALL other libs apart from ANTS_MOD1/mini_din
LibName52=ALL other libs apart from ANTS_MOD1/N8VEM
LibName53=ALL other libs apart from ANTS_MOD1/national
LibName54=ALL other libs apart from ANTS_MOD1/oldchips
LibName55=ALL other libs apart from ANTS_MOD1/opendous
LibName56=ALL other libs apart from ANTS_MOD1/propeller
LibName57=ALL other libs apart from ANTS_MOD1/RCA_video_jack
LibName58=ALL other libs apart from ANTS_MOD1/ref-packages
LibName59=ALL other libs apart from ANTS_MOD1/renesas21
LibName60=ALL other libs apart from ANTS_MOD1/S100connector
LibName61=ALL other libs apart from ANTS_MOD1/silabs
LibName62=ALL other libs apart from ANTS_MOD1/silabs-2
LibName63=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName64=ALL other libs apart from ANTS_MOD1/sn2032
LibName65=ALL other libs apart from ANTS_MOD1/stereo_jack
LibName66=ALL other libs apart from ANTS_MOD1/supports
LibName67=ALL other libs apart from ANTS_MOD1/transistor
LibName68=ALL other libs apart from ANTS_MOD1/transistor-power
LibName69=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName70=ALL other libs apart from ANTS_MOD1/XILINX
LibName71=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName72=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName73=numato/numato_kicad_lib
LibName74=ANTS1/ANTS1
[eeschema]
version=1
LibDir=../../Ants Librarys
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=ALL other libs apart from ANTS_MOD1/00N8VEM
LibName2=ALL other libs apart from ANTS_MOD1/4MEM-cache
LibName3=ALL other libs apart from ANTS_MOD1/65xxx
LibName4=ALL other libs apart from ANTS_MOD1/74ls-sergey
LibName5=ALL other libs apart from ANTS_MOD1/74xx
LibName6=ALL other libs apart from ANTS_MOD1/8563
LibName7=ALL other libs apart from ANTS_MOD1/babyM68K-cache
LibName8=ALL other libs apart from ANTS_MOD1/con-headers-jp
LibName9=ALL other libs apart from ANTS_MOD1/conn
LibName10=ALL other libs apart from ANTS_MOD1/con-vg
LibName11=ALL other libs apart from ANTS_MOD1/dallas-rtc
LibName12=ALL other libs apart from ANTS_MOD1/devices-sergey
LibName13=ALL other libs apart from ANTS_MOD1/dips-s
LibName14=ALL other libs apart from ANTS_MOD1/display-hp
LibName15=ALL other libs apart from ANTS_MOD1/diy_connectors
LibName16=ALL other libs apart from ANTS_MOD1/diy_switches
LibName17=ALL other libs apart from ANTS_MOD1/ECB-4PIO-cache
LibName18=ALL other libs apart from ANTS_MOD1/ECB-RAF2011-R08-cache
LibName19=ALL other libs apart from ANTS_MOD1/gd5420
LibName20=ALL other libs apart from ANTS_MOD1/HD15_B
LibName21=ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName22=ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName23=ALL other libs apart from ANTS_MOD1/intel
LibName24=ALL other libs apart from ANTS_MOD1/intel-8xxx
LibName25=ALL other libs apart from ANTS_MOD1/led
LibName26=ALL other libs apart from ANTS_MOD1/lm334z
LibName27=ALL other libs apart from ANTS_MOD1/lumiled
LibName28=ALL other libs apart from ANTS_MOD1/maxim
LibName29=ALL other libs apart from ANTS_MOD1/mcm414256-dip20
LibName30=ALL other libs apart from ANTS_MOD1/memory
LibName31=ALL other libs apart from ANTS_MOD1/memory-sergey
LibName32=ALL other libs apart from ANTS_MOD1/microchip
LibName33=ALL other libs apart from ANTS_MOD1/microchip_can
LibName34=ALL other libs apart from ANTS_MOD1/microchip_enet
LibName35=ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName36=ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName37=ALL other libs apart from ANTS_MOD1/microchip1
LibName38=ALL other libs apart from ANTS_MOD1/microchip-2
LibName39=ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName40=ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName41=ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName42=ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName43=ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName44=ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName45=ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName46=ALL other libs apart from ANTS_MOD1/micro-mc68000
LibName47=ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName48=ALL other libs apart from ANTS_MOD1/mini_din
LibName49=ALL other libs apart from ANTS_MOD1/motorola
LibName50=ALL other libs apart from ANTS_MOD1/N8VEM-KiCAD
LibName51=ALL other libs apart from ANTS_MOD1/o_analog
LibName52=ALL other libs apart from ANTS_MOD1/o_intel
LibName53=ALL other libs apart from ANTS_MOD1/o_memory
LibName54=ALL other libs apart from ANTS_MOD1/o_moto
LibName55=ALL other libs apart from ANTS_MOD1/o_ttl
LibName56=ALL other libs apart from ANTS_MOD1/o_zilog
LibName57=ALL other libs apart from ANTS_MOD1/oldchips
LibName58=ALL other libs apart from ANTS_MOD1/opendous
LibName59=ALL other libs apart from ANTS_MOD1/P112-parts
LibName60=ALL other libs apart from ANTS_MOD1/PIC-004-cache
LibName61=ALL other libs apart from ANTS_MOD1/pic18f67j60
LibName62=ALL other libs apart from ANTS_MOD1/propeller
LibName63=ALL other libs apart from ANTS_MOD1/ref-packages
LibName64=ALL other libs apart from ANTS_MOD1/renesas21
LibName65=ALL other libs apart from ANTS_MOD1/s100_Z80-cache
LibName66=ALL other libs apart from ANTS_MOD1/SBC-188
LibName67=ALL other libs apart from ANTS_MOD1/silabs
LibName68=ALL other libs apart from ANTS_MOD1/silabs-2
LibName69=ALL other libs apart from ANTS_MOD1/silabs-eth
LibName70=ALL other libs apart from ANTS_MOD1/sn2032
LibName71=ALL other libs apart from ANTS_MOD1/special
LibName72=ALL other libs apart from ANTS_MOD1/tms9918-AY38910
LibName73=ALL other libs apart from ANTS_MOD1/transistor
LibName74=ALL other libs apart from ANTS_MOD1/transistor-power
LibName75=ALL other libs apart from ANTS_MOD1/upd7220
LibName76=ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName77=ALL other libs apart from ANTS_MOD1/XC9572XL_44Pin-cache
LibName78=ALL other libs apart from ANTS_MOD1/XILINX
LibName79=ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName80=ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName81=ALL other libs apart from ANTS_MOD1/xilinxMOD1
LibName82=ALL other libs apart from ANTS_MOD1/Z8S180
LibName83=ALL other libs apart from ANTS_MOD1/z53c80
LibName84=KiCAD Libraries/74xx
LibName85=KiCAD Libraries/adc-dac
LibName86=KiCAD Libraries/analog_switches
LibName87=KiCAD Libraries/atmel
LibName88=KiCAD Libraries/audio
LibName89=KiCAD Libraries/brooktre
LibName90=KiCAD Libraries/cmos_ieee
LibName91=KiCAD Libraries/cmos4000
LibName92=KiCAD Libraries/conn
LibName93=KiCAD Libraries/contrib
LibName94=KiCAD Libraries/cypress
LibName95=KiCAD Libraries/device
LibName96=KiCAD Libraries/digital-audio
LibName97=KiCAD Libraries/display
LibName98=KiCAD Libraries/dsp
LibName99=KiCAD Libraries/gennum
LibName100=KiCAD Libraries/graphic
LibName101=KiCAD Libraries/intel
LibName102=KiCAD Libraries/interface
LibName103=KiCAD Libraries/linear
LibName104=KiCAD Libraries/memory
LibName105=KiCAD Libraries/microchip
LibName106=KiCAD Libraries/microchip1
LibName107=KiCAD Libraries/microcontrollers
LibName108=KiCAD Libraries/motorola
LibName109=KiCAD Libraries/opto
LibName110=KiCAD Libraries/philips
LibName111=KiCAD Libraries/power
LibName112=KiCAD Libraries/pspice
LibName113=KiCAD Libraries/regul
LibName114=KiCAD Libraries/siliconi
LibName115=KiCAD Libraries/special
LibName116=KiCAD Libraries/SymbolsSimilarEN60617+oldDIN617
LibName117=KiCAD Libraries/texas
LibName118=KiCAD Libraries/transf
LibName119=KiCAD Libraries/transistors
LibName120=KiCAD Libraries/ttl_ieee
LibName121=KiCAD Libraries/valves
LibName122=KiCAD Libraries/video
LibName123=KiCAD Libraries/xilinx
LibName124=KiCAD Libraries/xxx
LibName125=ANTS_MOD1
