update=8/25/2013 5:19:44 PM
last_client=pcbnew
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=H:/S6_BOARD2
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/00N8VEM
LibName2=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/4MEM-cache
LibName3=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/65xxx
LibName4=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/74ls-sergey
LibName5=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/74xx
LibName6=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/8563
LibName7=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/babyM68K-cache
LibName8=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/con-headers-jp
LibName9=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/conn
LibName10=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/con-vg
LibName11=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/dallas-rtc
LibName12=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/devices-sergey
LibName13=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/dips-s
LibName14=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/display-hp
LibName15=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_connectors
LibName16=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_switches
LibName17=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/ECB-4PIO-cache
LibName18=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/ECB-RAF2011-R08-cache
LibName19=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/gd5420
LibName20=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/HD15_B
LibName21=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName22=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName23=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/intel
LibName24=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/intel-8xxx
LibName25=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/led
LibName26=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/lm334z
LibName27=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/lumiled
LibName28=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/maxim
LibName29=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/mcm414256-dip20
LibName30=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/memory
LibName31=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/memory-sergey
LibName32=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip
LibName33=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_can
LibName34=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_enet
LibName35=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName36=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName37=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip1
LibName38=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-2
LibName39=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName40=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName41=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName42=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName43=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName44=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName45=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName46=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/micro-mc68000
LibName47=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName48=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/mini_din
LibName49=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/motorola
LibName50=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/N8VEM-KiCAD
LibName51=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_analog
LibName52=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_intel
LibName53=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_memory
LibName54=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_moto
LibName55=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_ttl
LibName56=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/o_zilog
LibName57=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/oldchips
LibName58=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/opendous
LibName59=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/P112-parts
LibName60=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/PIC-004-cache
LibName61=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/pic18f67j60
LibName62=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/propeller
LibName63=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/ref-packages
LibName64=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/renesas21
LibName65=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/s100_Z80-cache
LibName66=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/SBC-188
LibName67=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs
LibName68=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-2
LibName69=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-eth
LibName70=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/sn2032
LibName71=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/special
LibName72=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/tms9918-AY38910
LibName73=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor
LibName74=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor-power
LibName75=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/upd7220
LibName76=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName77=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/XC9572XL_44Pin-cache
LibName78=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/XILINX
LibName79=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName80=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName81=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinxMOD1
LibName82=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/Z8S180
LibName83=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/z53c80
LibName84=Ants Librarys/ANTS_MOD1
LibName85=74xgxx
LibName86=74xx
LibName87=ac-dc
LibName88=adc-dac
LibName89=analog_switches
LibName90=atmel
LibName91=audio
LibName92=brooktre
LibName93=cmos_ieee
LibName94=cmos4000
LibName95=conn
LibName96=contrib
LibName97=cypress
LibName98=dc-dc
LibName99=device
LibName100=digital-audio
LibName101=display
LibName102=dsp
LibName103=elec-unifil
LibName104=ftdi
LibName105=gennum
LibName106=graphic
LibName107=intel
LibName108=interface
LibName109=linear
LibName110=logo
LibName111=memory
LibName112=microchip
LibName113=microchip_pic10mcu
LibName114=microchip_pic12mcu
LibName115=microchip_pic16mcu
LibName116=microchip1
LibName117=microcontrollers
LibName118=motorola
LibName119=msp430
LibName120=nxp_armmcu
LibName121=opto
LibName122=philips
LibName123=power
LibName124=powerint
LibName125=pspice
LibName126=references
LibName127=regul
LibName128=relays
LibName129=sensors
LibName130=siliconi
LibName131=special
LibName132=stm8
LibName133=stm32
LibName134=supertex
LibName135=SymbolsSimilarEN60617+oldDIN617
LibName136=texas
LibName137=transf
LibName138=transistors
LibName139=ttl_ieee
LibName140=valves
LibName141=video
LibName142=xilinx
LibName143=xxx
[pcbnew]
version=1
LastNetListRead=SBC.net
UseCmpFile=1
PadDrill=0.812800000000
PadDrillOvalY=0.812800000000
PadSizeH=1.524000000000
PadSizeV=1.524000000000
PcbTextSizeV=2.032000000000
PcbTextSizeH=1.524000000000
PcbTextThickness=0.304800000000
ModuleTextSizeV=1.524000000000
ModuleTextSizeH=1.524000000000
ModuleTextSizeThickness=0.304800000000
SolderMaskClearance=0.254000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.100000000000
BoardOutlineThickness=0.381000000000
ModuleOutlineThickness=0.381000000000
[pcbnew/libraries]
LibDir=H:/S6_BOARD2/Ants Librarys
LibName1=H:/S6_BOARD2/Ants Librarys/ANTS1/ANTS1
LibName2=capacitors
LibName3=connect
LibName4=connectors_molex_serial_53047-A123
LibName5=dip_sockets
LibName6=discret
LibName7=display
LibName8=divers
LibName9=inductors
LibName10=led
LibName11=libcms
LibName12=muonde
LibName13=pga_sockets
LibName14=pin_array
LibName15=powerint
LibName16=smd_capacitors
LibName17=smd_crystal&oscillator
LibName18=smd_dil
LibName19=smd_resistors
LibName20=smd_soic_packages
LibName21=smd_ssop_packages
LibName22=smd_transistors
LibName23=sockets
LibName24=valves
LibName25=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/65xxx
LibName26=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/connecteurs
LibName27=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/con-vg
LibName28=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/dbrothers
LibName29=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/diode
LibName30=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_connectors
LibName31=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/diy_switches
LibName32=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/HD15_B
LibName33=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100
LibName34=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/hirose-fx2-100-2
LibName35=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/led
LibName36=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/lumiled
LibName37=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/maxim
LibName38=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip
LibName39=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_can
LibName40=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_enet
LibName41=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_mcp2120
LibName42=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip_pic16f716
LibName43=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-2
LibName44=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip16c7xx
LibName45=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-16f688
LibName46=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-18f258
LibName47=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-dspic
LibName48=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-enc28j60
LibName49=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-mcp125x-xxx
LibName50=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/microchip-pic18fxx5x
LibName51=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/micro-pic18xxx
LibName52=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/mini_din
LibName53=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/N8VEM
LibName54=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/national
LibName55=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/oldchips
LibName56=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/opendous
LibName57=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/propeller
LibName58=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/RCA_video_jack
LibName59=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/ref-packages
LibName60=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/renesas21
LibName61=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/S100connector
LibName62=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs
LibName63=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-2
LibName64=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/silabs-eth
LibName65=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/sn2032
LibName66=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/stereo_jack
LibName67=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/supports
LibName68=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor
LibName69=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/transistor-power
LibName70=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/Vocanson_display
LibName71=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/XILINX
LibName72=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_spartan3_virtex4_and_5
LibName73=H:/S6_BOARD2/Ants Librarys/ALL other libs apart from ANTS_MOD1/xilinx_xc9572xl-tq100
LibName74=MADE 1/ANTS2
LibName75=MADE 3/ANTS3
LibName76=numato/numato_kicad_lib
